//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APS.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding file.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding role.
        /// </summary>
        public static string AjoutRoles {
            get {
                return ResourceManager.GetString("AjoutRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must have minimum {1} and maximum {2} characters..
        /// </summary>
        public static string ChampLongeurMinMax {
            get {
                return ResourceManager.GetString("ChampLongeurMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be maximum {1} characters..
        /// </summary>
        public static string ChampLongueurMax {
            get {
                return ResourceManager.GetString("ChampLongueurMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is mandatory.
        /// </summary>
        public static string ChampObligatoire {
            get {
                return ResourceManager.GetString("ChampObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; must be identical.
        /// </summary>
        public static string ChampsDifferents {
            get {
                return ResourceManager.GetString("ChampsDifferents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect of invalid password.
        /// </summary>
        public static string ChangementMotPasseIncorrect {
            get {
                return ResourceManager.GetString("ChangementMotPasseIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection attempt failed.
        /// </summary>
        public static string ConnectionIncorrect {
            get {
                return ResourceManager.GetString("ConnectionIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid.
        /// </summary>
        public static string CourrielInvalide {
            get {
                return ResourceManager.GetString("CourrielInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation returned an error.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred creating the user.
        /// </summary>
        public static string CreationUtilisateur {
            get {
                return ResourceManager.GetString("CreationUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is smaller than {1}.
        /// </summary>
        public static string DateInferieur {
            get {
                return ResourceManager.GetString("DateInferieur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be lower than today&apos;s date.
        /// </summary>
        public static string DateInferieureAujourdhui {
            get {
                return ResourceManager.GetString("DateInferieureAujourdhui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid date.
        /// </summary>
        public static string DateSQL {
            get {
                return ResourceManager.GetString("DateSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be superior to the previous date.
        /// </summary>
        public static string DateSuperieurOuEgalAncienne {
            get {
                return ResourceManager.GetString("DateSuperieurOuEgalAncienne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion returned an error.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to have two identical {0} .
        /// </summary>
        public static string Doublons {
            get {
                return ResourceManager.GetString("Doublons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size is 200 Mo.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted file types is restricted to those listed below.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have the format: {1}.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is alphabetic characters only.
        /// </summary>
        public static string FormatUsername {
            get {
                return ResourceManager.GetString("FormatUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string Generale {
            get {
                return ResourceManager.GetString("Generale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** No Res found in Errors.resx ***.
        /// </summary>
        public static string Generique {
            get {
                return ResourceManager.GetString("Generique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting returned an error.
        /// </summary>
        public static string GetExportationGrille {
            get {
                return ResourceManager.GetString("GetExportationGrille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have {1} caracters.
        /// </summary>
        public static string LongueurMinimum {
            get {
                return ResourceManager.GetString("LongueurMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is too long.
        /// </summary>
        public static string NomFichierTropLong {
            get {
                return ResourceManager.GetString("NomFichierTropLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string NouveauMotPasseDifferent {
            get {
                return ResourceManager.GetString("NouveauMotPasseDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; are exclusive.
        /// </summary>
        public static string OuExclusif {
            get {
                return ResourceManager.GetString("OuExclusif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be between {1} et {2}.
        /// </summary>
        public static string PlageInvalide {
            get {
                return ResourceManager.GetString("PlageInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is invalid for &apos;{1}&apos;.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report error occurred.
        /// </summary>
        public static string Rapport {
            get {
                return ResourceManager.GetString("Rapport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading error occurred.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; required.
        /// </summary>
        public static string Requis {
            get {
                return ResourceManager.GetString("Requis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; required when &apos;{1}&apos; is used.
        /// </summary>
        public static string RequisDependant {
            get {
                return ResourceManager.GetString("RequisDependant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; or &apos;{1}&apos; required.
        /// </summary>
        public static string RequisOu {
            get {
                return ResourceManager.GetString("RequisOu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving.
        /// </summary>
        public static string Sauvegarde {
            get {
                return ResourceManager.GetString("Sauvegarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving user.
        /// </summary>
        public static string SauvegardeUtilisateur {
            get {
                return ResourceManager.GetString("SauvegardeUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be larger or eqal to &apos;{1}&apos;.
        /// </summary>
        public static string SuperieurOuEgal {
            get {
                return ResourceManager.GetString("SuperieurOuEgal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting role.
        /// </summary>
        public static string SuppressionRoles {
            get {
                return ResourceManager.GetString("SuppressionRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UsagerExisteDeja {
            get {
                return ResourceManager.GetString("UsagerExisteDeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password or User invalid.
        /// </summary>
        public static string UsagerMotPasseIncorrect {
            get {
                return ResourceManager.GetString("UsagerMotPasseIncorrect", resourceCulture);
            }
        }
    }
}
