//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APS.Resources.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbbrDays.
        /// </summary>
        public static string AbbrDays {
            get {
                return ResourceManager.GetString("AbbrDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbbrWeeks.
        /// </summary>
        public static string AbbrWeeks {
            get {
                return ResourceManager.GetString("AbbrWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbbrYears.
        /// </summary>
        public static string AbbrYears {
            get {
                return ResourceManager.GetString("AbbrYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcquisitionCosts.
        /// </summary>
        public static string AcquisitionCosts {
            get {
                return ResourceManager.GetString("AcquisitionCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionGrille.
        /// </summary>
        public static string ActionGrille {
            get {
                return ResourceManager.GetString("ActionGrille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        public static string Adjustment {
            get {
                return ResourceManager.GetString("Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdresseInstallation.
        /// </summary>
        public static string AdresseInstallation {
            get {
                return ResourceManager.GetString("AdresseInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher.
        /// </summary>
        public static string Afficher {
            get {
                return ResourceManager.GetString("Afficher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertes.
        /// </summary>
        public static string Alertes {
            get {
                return ResourceManager.GetString("Alertes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annule.
        /// </summary>
        public static string Annule {
            get {
                return ResourceManager.GetString("Annule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string Aucun {
            get {
                return ResourceManager.GetString("Aucun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AucunFiltre.
        /// </summary>
        public static string AucunFiltre {
            get {
                return ResourceManager.GetString("AucunFiltre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AucunResultatCdc.
        /// </summary>
        public static string AucunResultatCdc {
            get {
                return ResourceManager.GetString("AucunResultatCdc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AugmentationPointage.
        /// </summary>
        public static string AugmentationPointage {
            get {
                return ResourceManager.GetString("AugmentationPointage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AugmentationStatut.
        /// </summary>
        public static string AugmentationStatut {
            get {
                return ResourceManager.GetString("AugmentationStatut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string Autre {
            get {
                return ResourceManager.GetString("Autre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutreDocumentJoint.
        /// </summary>
        public static string AutreDocumentJoint {
            get {
                return ResourceManager.GetString("AutreDocumentJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutreNamToolTip.
        /// </summary>
        public static string AutreNamToolTip {
            get {
                return ResourceManager.GetString("AutreNamToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutreNumeroAssuranceMaladieAbbreviation.
        /// </summary>
        public static string AutreNumeroAssuranceMaladieAbbreviation {
            get {
                return ResourceManager.GetString("AutreNumeroAssuranceMaladieAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutreOrganes.
        /// </summary>
        public static string AutreOrganes {
            get {
                return ResourceManager.GetString("AutreOrganes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutresCentresHospitaliers.
        /// </summary>
        public static string AutresCentresHospitaliers {
            get {
                return ResourceManager.GetString("AutresCentresHospitaliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutreTelephone.
        /// </summary>
        public static string AutreTelephone {
            get {
                return ResourceManager.GetString("AutreTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avion.
        /// </summary>
        public static string Avion {
            get {
                return ResourceManager.GetString("Avion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        public static string Bienvenue {
            get {
                return ResourceManager.GetString("Bienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        public static string Bin {
            get {
                return ResourceManager.GetString("Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonCommande.
        /// </summary>
        public static string BonCommande {
            get {
                return ResourceManager.GetString("BonCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cacher.
        /// </summary>
        public static string Cacher {
            get {
                return ResourceManager.GetString("Cacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculsSurfaces.
        /// </summary>
        public static string CalculsSurfaces {
            get {
                return ResourceManager.GetString("CalculsSurfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorieArticle.
        /// </summary>
        public static string CategorieArticle {
            get {
                return ResourceManager.GetString("CategorieArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorieArticles.
        /// </summary>
        public static string CategorieArticles {
            get {
                return ResourceManager.GetString("CategorieArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellulaire.
        /// </summary>
        public static string Cellulaire {
            get {
                return ResourceManager.GetString("Cellulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangerMotPasse.
        /// </summary>
        public static string ChangerMotPasse {
            get {
                return ResourceManager.GetString("ChangerMotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAll.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeCouleur.
        /// </summary>
        public static string CodeCouleur {
            get {
                return ResourceManager.GetString("CodeCouleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePostal.
        /// </summary>
        public static string CodePostal {
            get {
                return ResourceManager.GetString("CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeVendeur.
        /// </summary>
        public static string CodeVendeur {
            get {
                return ResourceManager.GetString("CodeVendeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande.
        /// </summary>
        public static string Commande {
            get {
                return ResourceManager.GetString("Commande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires.
        /// </summary>
        public static string Commentaires {
            get {
                return ResourceManager.GetString("Commentaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommentaireSerologiePositive.
        /// </summary>
        public static string CommentaireSerologiePositive {
            get {
                return ResourceManager.GetString("CommentaireSerologiePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommentairesTestsSupplementaires.
        /// </summary>
        public static string CommentairesTestsSupplementaires {
            get {
                return ResourceManager.GetString("CommentairesTestsSupplementaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp.
        /// </summary>
        public static string Comp {
            get {
                return ResourceManager.GetString("Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibilite.
        /// </summary>
        public static string Compatibilite {
            get {
                return ResourceManager.GetString("Compatibilite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompatibiliteCroisee.
        /// </summary>
        public static string CompatibiliteCroisee {
            get {
                return ResourceManager.GetString("CompatibiliteCroisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompCroisee.
        /// </summary>
        public static string CompCroisee {
            get {
                return ResourceManager.GetString("CompCroisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompCroiseeFinale.
        /// </summary>
        public static string CompCroiseeFinale {
            get {
                return ResourceManager.GetString("CompCroiseeFinale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompCroiseeRequise.
        /// </summary>
        public static string CompCroiseeRequise {
            get {
                return ResourceManager.GetString("CompCroiseeRequise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptabilite.
        /// </summary>
        public static string Comptabilite {
            get {
                return ResourceManager.GetString("Comptabilite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionPaiement.
        /// </summary>
        public static string ConditionPaiement {
            get {
                return ResourceManager.GetString("ConditionPaiement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmationCompletee.
        /// </summary>
        public static string ConfirmationCompletee {
            get {
                return ResourceManager.GetString("ConfirmationCompletee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmationMotPasseOublie.
        /// </summary>
        public static string ConfirmationMotPasseOublie {
            get {
                return ResourceManager.GetString("ConfirmationMotPasseOublie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string Confirmer {
            get {
                return ResourceManager.GetString("Confirmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmerResultats.
        /// </summary>
        public static string ConfirmerResultats {
            get {
                return ResourceManager.GetString("ConfirmerResultats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connecter {
            get {
                return ResourceManager.GetString("Connecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur.
        /// </summary>
        public static string Couleur {
            get {
                return ResourceManager.GetString("Couleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs.
        /// </summary>
        public static string Couleurs {
            get {
                return ResourceManager.GetString("Couleurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Courriel {
            get {
                return ResourceManager.GetString("Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cout.
        /// </summary>
        public static string Cout {
            get {
                return ResourceManager.GetString("Cout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couts.
        /// </summary>
        public static string Couts {
            get {
                return ResourceManager.GetString("Couts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoutTransport.
        /// </summary>
        public static string CoutTransport {
            get {
                return ResourceManager.GetString("CoutTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateCommande.
        /// </summary>
        public static string DateCommande {
            get {
                return ResourceManager.GetString("DateCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateFacture.
        /// </summary>
        public static string DateFacture {
            get {
                return ResourceManager.GetString("DateFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateReception.
        /// </summary>
        public static string DateReception {
            get {
                return ResourceManager.GetString("DateReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconnexion.
        /// </summary>
        public static string Deconnexion {
            get {
                return ResourceManager.GetString("Deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        public static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string Enregistrer {
            get {
                return ResourceManager.GetString("Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entreprise.
        /// </summary>
        public static string Entreprise {
            get {
                return ResourceManager.GetString("Entreprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essence.
        /// </summary>
        public static string Essence {
            get {
                return ResourceManager.GetString("Essence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essences.
        /// </summary>
        public static string Essences {
            get {
                return ResourceManager.GetString("Essences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcelExport.
        /// </summary>
        public static string ExcelExport {
            get {
                return ResourceManager.GetString("ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturation.
        /// </summary>
        public static string Facturation {
            get {
                return ResourceManager.GetString("Facturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturations.
        /// </summary>
        public static string Facturations {
            get {
                return ResourceManager.GetString("Facturations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeuilleDeTravail.
        /// </summary>
        public static string FeuilleDeTravail {
            get {
                return ResourceManager.GetString("FeuilleDeTravail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fini.
        /// </summary>
        public static string Fini {
            get {
                return ResourceManager.GetString("Fini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finis.
        /// </summary>
        public static string Finis {
            get {
                return ResourceManager.GetString("Finis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormatDate.
        /// </summary>
        public static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormatDateTime.
        /// </summary>
        public static string FormatDateTime {
            get {
                return ResourceManager.GetString("FormatDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        public static string Fournisseur {
            get {
                return ResourceManager.GetString("Fournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseurs.
        /// </summary>
        public static string Fournisseurs {
            get {
                return ResourceManager.GetString("Fournisseurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GradeExplanation.
        /// </summary>
        public static string GradeExplanation {
            get {
                return ResourceManager.GetString("GradeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GradeMessage.
        /// </summary>
        public static string GradeMessage {
            get {
                return ResourceManager.GetString("GradeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        public static string Grades {
            get {
                return ResourceManager.GetString("Grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupes.
        /// </summary>
        public static string Groupes {
            get {
                return ResourceManager.GetString("Groupes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installeur.
        /// </summary>
        public static string Installeur {
            get {
                return ResourceManager.GetString("Installeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installeurs.
        /// </summary>
        public static string Installeurs {
            get {
                return ResourceManager.GetString("Installeurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventaire.
        /// </summary>
        public static string Inventaire {
            get {
                return ResourceManager.GetString("Inventaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventaireAnnuelAvecNotes.
        /// </summary>
        public static string InventaireAnnuelAvecNotes {
            get {
                return ResourceManager.GetString("InventaireAnnuelAvecNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventaireAnnuelSansNotes.
        /// </summary>
        public static string InventaireAnnuelSansNotes {
            get {
                return ResourceManager.GetString("InventaireAnnuelSansNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventaireNul.
        /// </summary>
        public static string InventaireNul {
            get {
                return ResourceManager.GetString("InventaireNul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventaires {
            get {
                return ResourceManager.GetString("Inventaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string MenuGestion {
            get {
                return ResourceManager.GetString("MenuGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string MenuProfit {
            get {
                return ResourceManager.GetString("MenuProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedBy.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MotPasse {
            get {
                return ResourceManager.GetString("MotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string MotPasseActuel {
            get {
                return ResourceManager.GetString("MotPasseActuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string MotPasseConfirmer {
            get {
                return ResourceManager.GetString("MotPasseConfirmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string MotPasseConfirmerNouveau {
            get {
                return ResourceManager.GetString("MotPasseConfirmerNouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string MotPasseNouveau {
            get {
                return ResourceManager.GetString("MotPasseNouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string NomUsager {
            get {
                return ResourceManager.GetString("NomUsager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NouvelUtilisateur {
            get {
                return ResourceManager.GetString("NouvelUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onglet.
        /// </summary>
        public static string Onglet {
            get {
                return ResourceManager.GetString("Onglet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password ?.
        /// </summary>
        public static string OublieMotPasse {
            get {
                return ResourceManager.GetString("OublieMotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFExport.
        /// </summary>
        public static string PDFExport {
            get {
                return ResourceManager.GetString("PDFExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrefComm.
        /// </summary>
        public static string PrefComm {
            get {
                return ResourceManager.GetString("PrefComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string Preference {
            get {
                return ResourceManager.GetString("Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefixe {
            get {
                return ResourceManager.GetString("Prefixe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preleve.
        /// </summary>
        public static string Preleve {
            get {
                return ResourceManager.GetString("Preleve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorite.
        /// </summary>
        public static string Priorite {
            get {
                return ResourceManager.GetString("Priorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrioriteAppliquee.
        /// </summary>
        public static string PrioriteAppliquee {
            get {
                return ResourceManager.GetString("PrioriteAppliquee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrioriteMajuscules.
        /// </summary>
        public static string PrioriteMajuscules {
            get {
                return ResourceManager.GetString("PrioriteMajuscules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrioriteStatutEgal.
        /// </summary>
        public static string PrioriteStatutEgal {
            get {
                return ResourceManager.GetString("PrioriteStatutEgal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductVisibility.
        /// </summary>
        public static string ProductVisibility {
            get {
                return ResourceManager.GetString("ProductVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Rapport {
            get {
                return ResourceManager.GetString("Rapport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMe.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reponse.
        /// </summary>
        public static string Reponse {
            get {
                return ResourceManager.GetString("Reponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultat.
        /// </summary>
        public static string Resultat {
            get {
                return ResourceManager.GetString("Resultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaisieModification.
        /// </summary>
        public static string SaisieModification {
            get {
                return ResourceManager.GetString("SaisieModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SauvegarderModifier.
        /// </summary>
        public static string SauvegarderModifier {
            get {
                return ResourceManager.GetString("SauvegarderModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconde.
        /// </summary>
        public static string Seconde {
            get {
                return ResourceManager.GetString("Seconde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminer.
        /// </summary>
        public static string Terminer {
            get {
                return ResourceManager.GetString("Terminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string TitreGestionUtilisateurs {
            get {
                return ResourceManager.GetString("TitreGestionUtilisateurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitreLogin {
            get {
                return ResourceManager.GetString("TitreLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string TitreRecherche {
            get {
                return ResourceManager.GetString("TitreRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string TitreUtilisateur {
            get {
                return ResourceManager.GetString("TitreUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        public static string Tous {
            get {
                return ResourceManager.GetString("Tous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UncheckAll.
        /// </summary>
        public static string UncheckAll {
            get {
                return ResourceManager.GetString("UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
