//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APS.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string AucuneDonnee {
            get {
                return ResourceManager.GetString("AucuneDonnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string ConfirmationNavigation {
            get {
                return ResourceManager.GetString("ConfirmationNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow email instructions.
        /// </summary>
        public static string CourrielReinitialiserMotPasse {
            get {
                return ResourceManager.GetString("CourrielReinitialiserMotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password procedure underway.
        /// </summary>
        public static string CourrielReinitialiserMotPasseBody {
            get {
                return ResourceManager.GetString("CourrielReinitialiserMotPasseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APS: Reset password.
        /// </summary>
        public static string CourrielReinitialiserMotPasseSubject {
            get {
                return ResourceManager.GetString("CourrielReinitialiserMotPasseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation effective.
        /// </summary>
        public static string CreationEffectuee {
            get {
                return ResourceManager.GetString("CreationEffectuee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date mandatory.
        /// </summary>
        public static string DateDebutObligatoire {
            get {
                return ResourceManager.GetString("DateDebutObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date mandatory.
        /// </summary>
        public static string DateFinObligatoire {
            get {
                return ResourceManager.GetString("DateFinObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of list.
        /// </summary>
        public static string FinDeListe {
            get {
                return ResourceManager.GetString("FinDeListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern summer time.
        /// </summary>
        public static string HeureEte {
            get {
                return ResourceManager.GetString("HeureEte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Eastern time.
        /// </summary>
        public static string HeureNormale {
            get {
                return ResourceManager.GetString("HeureNormale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked.
        /// </summary>
        public static string LockoutText {
            get {
                return ResourceManager.GetString("LockoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string ModificationEffectuee {
            get {
                return ResourceManager.GetString("ModificationEffectuee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent status for {0}.
        /// </summary>
        public static string NouveauStatutUrgent {
            get {
                return ResourceManager.GetString("NouveauStatutUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user is active in another window.
        /// </summary>
        public static string SessionActive {
            get {
                return ResourceManager.GetString("SessionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user is active on another session. Kill?.
        /// </summary>
        public static string SessionKill {
            get {
                return ResourceManager.GetString("SessionKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string TitleGestion {
            get {
                return ResourceManager.GetString("TitleGestion", resourceCulture);
            }
        }
    }
}
